#!/bin/sh -e

# NOTE: This script is run as both config and preinst

my_action=

case "$1" in
configure)
	if [ "$2" = "" ]; then
		my_action=new_install
	else
		my_action=upgrade
	fi
	;;
install) my_action=new_install; ;;
upgrade) my_action=upgrade; ;;
esac

case "$my_action" in
new_install)
	# New install - just accept all established protocol changes, as they're not changes for us
	. /usr/share/debconf/confmodule
	db_set bitcoin/rdts true
	;;
upgrade)
	# Downgrading, upgrading or reinstalling. Check that RDTS is okay.
	. /usr/share/debconf/confmodule
	
	db_get bitcoin/rdts
	if [ "$RET" = "false" ]; then
		# User said no at some point before
		# Can't install under those conditions, so ask again
		db_fset bitcoin/rdts seen false
	fi
	if [ "$RET" != "true" ]; then
		db_input critical bitcoin/rdts || true
		db_go
		
		common_err() {
			echo '' >&2
			echo "This version of Bitcoin Knots applies the BIP110 (RDTS) network upgrade, which fixes critical vulnerabilities in long-standing network design, but $1." >&2
			echo '' >&2
			echo "Important: Because this upgrade already has broad community support, skipping or delaying this package update does not reject it. Running outdated software after any network upgrade only leaves your node vulnerable to displaying fake or fraudulent transactions. To effectively reject this upgrade, you need to run alternative software designed to split away from the upgraded network." >&2
			echo '' >&2
			echo "For more information, see: https://bitcoinknots.org/learn/2026-rdts" >&2
			echo '' >&2
		}
		
		if ! db_get bitcoin/rdts || [ -z "$RET" ]; then
			# Failed to ask user. Abort
			common_err 'explicit user confirmation has not been configured'
			echo "Try 'dpkg-reconfigure debconf' to select a frontend other than noninteractive" >&2
			echo "to confirm this upgrade." >&2
			echo '' >&2
			exit 1
		fi
		if [ "$RET" = "false" ] || [ "$RET" = "no" ]; then
			# User answered no. Abort
			common_err 'you have chosen to reject it'
			echo "Upgrade aborted." >&2
			echo '' >&2
			exit 1
		fi
	fi
	;;
esac
